#-- Script shortcuts --#
alias backup='~/repos/bash_scripts/backup.sh'
alias bu='backup'

alias digitalize='~/repos/bash_scripts/digitalize.sh'
alias digi='digitalize'

alias opn="~/repos/bash_scripts/opn.sh"

alias duu="~/repos/bash_scripts/duu.sh"

alias gstatus="~/repos/bash_scripts/gstatus2.sh"
alias gits="gstatus"

alias scraper="~/repos/bash_scripts/scraper.sh"

alias ufiles="~/repos/my-arch/update.sh"
alias pfiles="~/repos/my-arch/push.sh"



#-- Command aliases --#
alias ls='exa -g'
alias ll='ls -la --git'
alias grep='grep --color=auto'
alias tree='exa -T'
alias treee='exa -TDL 2'
alias sc="shellcheck"
alias cmatrix="cmatrix -absu 9"
alias ff="fastfetch"

alias wipconfig="powershell.exe ipconfig | tail -n 10"
alias winip="wipconfig"
#alias xlaunch="powershell.exe -Command '& \"C:\\Program Files\\VcXsrv\\xlaunch.exe\"'"
#alias xl="xlaunch"

alias python="python3"

alias win="powershell.exe"

alias wopen="explorer.exe"



#-- Common directories --#
WINU='/mnt/c/Users/{{WIN_USER}}/'
WIND='/mnt/c/Users/{{WIN_USER}}/Downloads/'
WINK='/mnt/c/Users/{{WIN_USER}}/OneDrive/Desktop/'

alias winu='cd $WINU'
alias wind='cd $WIND'
alias wink='cd $WINK'

alias msv='cd /mnt/c/Users/{{WIN_USER}}/OneDrive/Desktop/Obsidian_vaults/MySuperVault/'
alias mvs='msv && mv IMG_* System/Assets/'

alias dnd='cd /mnt/c/Users/{{WIN_USER}}/OneDrive/Desktop/Obsidian_vaults/MySuperVault/Efforts/DnD && nvim'

alias repos="cd ~/repos/"

#-- Common files --#
alias al="nvim ~/.bash_aliases"
alias rc="source ~/.bashrc"
alias nrc="nvim ~/.bashrc"
alias todo="bat ~/TODO.md"
alias ntodo="nvim ~/TODO.md"
