#!/bin/bash
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Prompt customization
#export PS1='┌[\e[92m\u@\h \e[94m\w\e[39m \A] ($(jobs | wc -l))\n└─\$ '
is_ssh() {
    if [ -n "$SSH_CLIENT" ]; then
        echo -e "\e[90m@\e[91m$HOSTNAME"
    fi
}
is_root_color() {
    if [ "$UID" -eq 0 ]; then
        echo -e "\e[91m"
    else
        echo -e "\e[93m"
    fi
}
is_root_prompt() {
    if [ "$UID" -eq 0 ]; then
        echo "# "
    else
        echo "> "
    fi
}
number_jobs() {
    j=$(jobs | wc -l)
    if [ $j -ge 1 ]; then
        echo "${j} "
    fi
}

export PS1='  $(is_root_color)\u$(is_ssh)\e[39m $(number_jobs)\e[94m\w\e[39m\n$(is_root_prompt)'

# Vi mode
set -o vi
bind -m vi-insert '"\C-l": clear-screen'

# fzf
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash


# X-server stuff
export LIBGL_ALWAYS_INDIRECT=1

# ghcup-env
[ -f "/home/wamoya/.ghcup/env" ] && source "/home/wamoya/.ghcup/env"

# Load custom aliases
source ~/.bash_aliases


# Login routine
pokeget random --hide-name
cat ~/TODO.md
